<?php

/**
 * @file
 * Contains dcom_menu.module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function dcom_menu_preprocess_image_formatter(&$variables) {
  /** @var \Drupal\image\Plugin\Field\FieldType\ImageItem $item */
  $item = $variables['item'];
  $target_entity_type = $item->getFieldDefinition()->getTargetEntityTypeId();
  $field_name = $item->getFieldDefinition()->getName();
  if ($target_entity_type == 'taxonomy_term'
    && $field_name == 'field_image'
    && $variables['image_style'] == 'megamenu') {
    $variables['item_attributes']['data-lazy-load'] = TRUE;
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function dcom_menu_preprocess_image(&$variables) {
  if (!empty($variables['attributes']['data-lazy-load'])) {
    $variables['attributes']['data-src'] = $variables['attributes']['src'];
    $variables['attributes']['class'][] = 'image-lazy-load';
    unset($variables['attributes']['data-lazy-load']);
    unset($variables['attributes']['src']);
  }
}
