version: "2.1"

services:
  mariadb:
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 1
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
#      PHP_BLACKFIRE: 1
#      COMPOSER_AUTH: '{"github-oauth": {"github.com": "xxx"}}'
      PHP_BLACKFIRE: 1
    volumes:
      - ./code:/var/www/html:cached
    working_dir: /var/www/html/web

  nginx:
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
    volumes:
      - ./code:/var/www/html:cached
# Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=diamondcbdcommerce_nginx_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:diamondcommerce.docker.localhost,mbio.diamondcommerce.docker.localhost,diamondcbd.diamondcommerce.docker.localhost,medipets.diamondcommerce.docker.localhost,medsbiotech.com,www.medsbiotech.com,chillgummies.diamondcommerce.docker.localhost,relaxgummies.diamondcommerce.docker.localhost,cbdliquidgold.diamondcommerce.docker.localhost,diamondcbdoil.diamondcommerce.docker.localhost,chongchoicecbd.diamondcommerce.docker.localhost,56cbd.diamondcommerce.docker.localhost,bluecbd.diamondcommerce.docker.localhost,diamondhemp.diamondcommerce.docker.localhost'

  adminer:
    image: wodby/adminer:4.3-1.1.0
    environment:
      ADMINER_SALT: adminer-salt
    labels:
      - 'traefik.backend=diamondcbdcommerce_adminer_1'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:adminer.diamondcommerce.docker.localhost'

  solr:
    labels:
      - 'traefik.backend=diamondcbdcommerce_solr_1'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.diamondcommerce.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=diamondcbdcommerce_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.diamondcommerce.docker.localhost'

  gulp:
    build: docker/gulp
    environment:
      GULP_THEME: mbio
    volumes_from:
      - php
    ports:
      - "3000:3000"
      - "3001:3001"
    working_dir: /var/www/html/web/themes/custom

  blackfire:
    image: blackfire/blackfire
    environment:
      # Put your server ID and token here.
      BLACKFIRE_SERVER_ID: XXX
      BLACKFIRE_SERVER_TOKEN: XXX
