config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.user.user.commerce_remote_id
    - field.field.user.user.field_first_name
    - field.field.user.user.field_last_name
    - field.field.user.user.user_picture
  module:
    - file
    - user
id: user.user.default
targetEntityType: user
bundle: user
mode: default
content:
  field_first_name:
    weight: 0
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    type: string
    region: content
  field_last_name:
    weight: 1
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    type: string
    region: content
  masquerade:
    weight: 50
    region: content
hidden:
  commerce_remote_id: true
  langcode: true
  member_for: true
  profile_customer: true
  user_picture: true
