config_rewrite: replace
langcode: en
status: true
dependencies:
  config:
    - field.field.user.user.commerce_remote_id
    - field.field.user.user.field_first_name
    - field.field.user.user.field_last_name
    - field.field.user.user.user_picture
  module:
    - file
    - path
    - user
id: user.user.default
targetEntityType: user
bundle: user
mode: default
content:
  account:
    weight: 0
    region: content
    settings: {  }
    third_party_settings: {  }
  contact:
    weight: 5
    region: content
  field_first_name:
    weight: 1
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  field_last_name:
    weight: 2
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
    type: string_textfield
    region: content
  path:
    type: path
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  commerce_remote_id: true
  langcode: true
  language: true
  timezone: true
  user_picture: true
