version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "nginx-vhosts:/etc/nginx/vhost.d"
      - "nginx-html:/usr/share/nginx/html"
      - "nginx-certs:/etc/nginx/certs"
      - "/opt/nginx/htpasswd:/etc/nginx/htpasswd"
      - "/var/run/docker.sock:/tmp/docker.sock:ro"
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always
    networks:
      - "nginx-proxy"

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes_from:
      - "nginx-proxy"
    networks:
      - "nginx-proxy"

volumes:
  nginx-vhosts:
  nginx-html:
  nginx-certs:

networks:
  nginx-proxy:
    external:
      name: nginx-proxy
