dependencies:
  config:
  - field.field.profile.customer.field_phone_number
  module:
  - telephone
content:
  field_phone_number:
    weight: 1
    settings:
      placeholder: ''
    third_party_settings: {  }
    type: telephone_default
    region: content
