<?php

/**
 * @file
 * Contains dcom_recent_purchase_popup.module.
 */

use Drupal\Core\Entity\Query\Sql\Query;

/**
 * Implements hook_commerce_recent_purchase_popup_query_alter().
 */
function dcom_recent_purchase_popup_commerce_recent_purchase_popup_query_alter(Query &$query) {
  // Adding by domain filter.
  $query->condition('field_domain', \Drupal::service('domain.negotiator')->getActiveId());
}
